version: '3.7'

services:
  backend:
    image: paymentq
    build:
      context: ./Payment.Api
      args: VITE_BASE_URL=https://pay-back.babajideadedeji.com
    restart: always
    container_name: coon
    ports:
      - 5001:80
  frontend:
    depends_on:
      - backend
    image: paymentq-front
    build:
      context: ./Payment.Client
    container_name: coon-front
    ports:
      - 4000:80
    environment:
      - VITE_BASE_URL=https://pay-back.babajideadedeji.com
