version: '3.7'

services:
  backend:
    image: paymentq
    build:
      context: ./Payment.Api
    restart: always
    container_name: coon
    ports:
      - 5001:80

  frontend:
    depends_on:
      - backend
    image: paymentq-front
    build:
      context: ./Payment.Client
      args:
        - VITE_BASE_URL=https://pay-back.babajideadedeji.com/api/v1
    restart: always
    container_name: coon-front
    ports:
      - 4000:80
